### PR TITLE
Add 'Hi Scout' Message on new Session

### LINKED ISSUE #64: Display message by Scout for every new session
- At the start of every new session, we can display the first message `Hi, I am Scout. I can help you with the given options`
- It gives user a starting point to chat with Scout, instead of a blank window

### PR DESCRIPTION
**Pull request by janiew**
Fixes #64

### CODE REVIEW

**Comment by janiew** [comment]
I was running into some technical issues with sending the message on chatbot window startup and put this in as a compromise. If the user sends the message in the textbox they will recieve a message from scout to that effect. If you think this solution is too obtrusive, I can go back and try to implement the original spec

**Comment by Noah-Huppert** [comment]
> I was running into some technical issues with sending the message on chatbot window startup and put this in as a compromise. If the user sends the message in the textbox they will recieve a message from scout to that effect. If you think this solution is too obtrusive, I can go back and try to implement the original spec

I would leave this to @VaishnaviHire: does this change close #64 ?

Currently it looks like:

**Comment by Noah-Huppert** [comment]
My 2 cents is that this is a good compromise but we should also have scout send an initial message. Keep this and do #64.

**Comment by janiew** [comment]
Merged through #77

**Pull request closed without merging**
